# Generated by Django 6.1.1 on 2026-09-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurai', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
