# Generated by Django 6.1.1 on 2026-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, verbose_name='Автор книги')),
                ('title', models.CharField(max_length=70, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена книги')),
                ('year', models.DateField(verbose_name='Год выпуска книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
