# Generated by Django 6.1.1 on 2026-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=130, verbose_name='Бренд')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('mileage', models.IntegerField(max_length=10, verbose_name='Пробег')),
                ('transmission_type', models.CharField(max_length=80, verbose_name='Тип передачи')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Тип топлива')),
                ('car_type', models.CharField(max_length=120, verbose_name='Тип машины(легковая, грузовая)')),
                ('car_description', models.TextField(blank=True, default='Без описания', verbose_name='Описание машины')),
                ('state', models.TextField(blank=True, default='Не указано', verbose_name='Состояние')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Год выхода')),
                ('price', models.IntegerField(max_length=15, verbose_name='Цена(в долларах)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_image/', verbose_name='Изображение машины')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
