# Generated by Django 6.1.1 on 2026-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurai', '0003_rename_student_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
