# Generated by Django 6.1.1 on 2026-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Имя сайта')),
                ('site_logo', models.ImageField(upload_to='media/', verbose_name='Лого сайта')),
                ('locate', models.CharField(max_length=250, verbose_name='Локация')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефонный номер')),
                ('email', models.CharField(max_length=250, verbose_name='Электронная почта')),
                ('reseption', models.CharField(max_length=250, verbose_name='О ресепшене')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
