# Generated by Django 6.1.1 on 2026-09-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='site_logo',
        ),
    ]
