# Generated by Django 6.1.1 on 2026-09-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0002_remove_settings_site_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='reseption',
            new_name='reception',
        ),
    ]
