# Generated by Django 6.1.1 on 2026-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0003_rename_reseption_settings_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='short_description',
            field=models.CharField(default=1, max_length=300, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
