# Generated by Django 6.1.1 on 2026-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0004_settings_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=250, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Banner/', verbose_name='Фото')),
            ],
        ),
    ]
