# Generated by Django 6.1.1 on 2026-09-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0005_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=250, verbose_name='Подзаголовок')),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
