# Generated by Django 6.1.1 on 2026-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0006_advantages_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=250, verbose_name='Подзаголовок')),
                ('rooms_count', models.IntegerField(verbose_name='Количество номеров')),
                ('rating', models.FloatField(verbose_name='Рейтинг гостей(до 10)')),
                ('works_age', models.IntegerField(verbose_name='Лет работы')),
                ('image', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'Характеристика отеля',
                'verbose_name_plural': 'Характеристики отеля',
            },
        ),
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name': 'Преимущетсво', 'verbose_name_plural': 'Преимущетсва'},
        ),
    ]
