# Generated by Django 6.1.1 on 2026-09-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0007_about_hotel_alter_advantages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_description', models.TextField(verbose_name='Описание комнат')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото номера')),
                ('room_class', models.CharField(verbose_name='Класс')),
                ('room_description', models.TextField(verbose_name='Описание комнаты')),
                ('guests_count', models.IntegerField(verbose_name='Количество гостей')),
                ('square', models.IntegerField(verbose_name='Площадь')),
                ('advantage', models.CharField(max_length=250, verbose_name='Преимущество')),
                ('price', models.IntegerField(verbose_name='Цена(ночь)')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='Фото'),
        ),
    ]
