# Generated by Django 6.1.1 on 2026-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0008_galery_rooms_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(upload_to='rooms/', verbose_name='Фото номера'),
        ),
    ]
