# Generated by Django 6.1.1 on 2026-09-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0009_alter_galery_image_alter_rooms_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='rooms_description',
        ),
    ]
