# Generated by Django 6.1.1 on 2026-09-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0010_rename_room_description_rooms_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galery',
            new_name='Gallery',
        ),
    ]
