# Generated by Django 6.1.1 on 2026-09-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0011_rename_galery_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
